Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
